---
- hosts: localhost
  gather_facts: true
  vars:
    # Required Os Packages
    LIST_OS_PACKAGES:
      Generic:
        - sysstat
        - unzip
        - sudo
      ClearLinux:
        - "network-basic"
      Debian:
        - "dnsutils"
      Archlinux:
        - "bind"
    # Read Local configuration files
    BENCHMARK_CONFIG: "{{ lookup('file', 'config/testcases.json') | from_json }}"
    SYNCTEST_CONFIG: "{{ lookup('file', 'config/local_config.yml') | from_yaml }}"
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter sudo password"
      confirm: yes
      private: yes
    - name: confirmation
      prompt: |
        |||||||||||||||||||||||||||||||||||||||||||||||||||||
        This script will
          - Stop all chia processes of user "{{ SYNCTEST_CONFIG.CHIA_OS_GROUP }}"
          - Replace any existing chia SW installation at "{{ SYNCTEST_CONFIG.CHIA_SW_PATH }}" with branch/tag "{{ SYNCTEST_CONFIG.CHIA_BRANCH }}"
          - Remove chia db "{{ SYNCTEST_CONFIG.BLOCKCHAIN_DB_PATH }}/{{ SYNCTEST_CONFIG.BLOCKCHAIN_DB_NAME }}" and related -shm, -journal, -wal files
          - If not already available, download the required database file for scenario "{{ SYNCTEST_CONFIG.SCENARIO }}"
            The prepared database files are vacuumed and all relevant indexes are droped.
          - Local configuration files are located at "{{ SYNCTEST_CONFIG.ANSIBLE_HOME_PATH }}/config"
          - Run the following testcases: 
              {{ BENCHMARK_CONFIG.ACTIVE_TESTCASES }}
            Check file "config/testcases.json" for further information regarding testcases.
          - Logfiles will be written to:
            .) chia 
               debug.log in "{{ SYNCTEST_CONFIG.ANSIBLE_LOG_PATH }}/current/chia"
            .) sar 
               raw data in "{{ SYNCTEST_CONFIG.ANSIBLE_LOG_PATH }}/current/sa"
               csv export "{{ SYNCTEST_CONFIG.ANSIBLE_LOG_PATH }}/current/*.sa.csv"
               svg reports "{{ SYNCTEST_CONFIG.ANSIBLE_LOG_PATH }}/current/*.sa.svg"
            .) testcase
               run info "{{ SYNCTEST_CONFIG.ANSIBLE_LOG_PATH }}/current/*_ansible_run.csv"
          - Depending on the hosts hardware, selected scenario and testcases, the scripts execution can last from a few minutes to several days.
        |||||||||||||||||||||||||||||||||||||||||||||||||||||
        Proceed? (yes/no) 
      private: no
  pre_tasks:
    - name: "Fail if no confirmation was given"
      fail:
        msg: "No confirmation given ... aborting."
      when: "confirmation|lower != 'yes'"
    - name: "Get timestamp for execution"
      ansible.builtin.shell: |
        date +%Y-%m-%d_%H:%M:%S
      register: timestamp_started
    - name: "Install required OS packages"
      ansible.builtin.include_role:
        name: install_os_package
      loop: 
        - "{{ LIST_OS_PACKAGES[\"Generic\"] }}"
        - "{{ LIST_OS_PACKAGES[ansible_facts.os_family] }}"
      loop_control:
        loop_var: PACK_TO_INSTALL_OS_FAMILY
    - name: "Set Local Config Variables" 
      ansible.builtin.set_fact:
        CHIA_OS_USER: "{{ SYNCTEST_CONFIG.CHIA_OS_USER }}"
        CHIA_OS_GROUP: "{{ SYNCTEST_CONFIG.CHIA_OS_GROUP }}"
        CHIA_GIT_REPO: "{{ SYNCTEST_CONFIG.CHIA_GIT_REPO }}"
        CHIA_BRANCH: "{{ SYNCTEST_CONFIG.CHIA_BRANCH }}"
        SCENARIO: "{{ SYNCTEST_CONFIG.SCENARIO }}"
        SADC_BIN_PATH: "{{ SYNCTEST_CONFIG.SADC_BIN_PATH }}"
        BLOCKCHAIN_DB_NAME: "{{ SYNCTEST_CONFIG.BLOCKCHAIN_DB_NAME }}"
        BLOCKCHAIN_DB_PATH: "{{ SYNCTEST_CONFIG.BLOCKCHAIN_DB_PATH }}"
        OS_USER_HOME: "{{ SYNCTEST_CONFIG.OS_USER_HOME }}"
        ANSIBLE_HOME_PATH: "{{ SYNCTEST_CONFIG.ANSIBLE_HOME_PATH }}"
        CHIA_SW_PATH: "{{ SYNCTEST_CONFIG.CHIA_SW_PATH }}"
        ANSIBLE_LOG_PATH: "{{ SYNCTEST_CONFIG.ANSIBLE_LOG_PATH }}"
    - name: debug
      debug:
        msg:
          - "{{ CHIA_OS_USER }}"
          - "{{ CHIA_OS_GROUP }}"
          - "{{ CHIA_GIT_REPO }}"
          - "{{ CHIA_BRANCH }}"
          - "{{ SCENARIO }}"
          - "{{ SADC_BIN_PATH }}"
          - "{{ BLOCKCHAIN_DB_NAME }}"
          - "{{ OS_USER_HOME }}"
          - "{{ BLOCKCHAIN_DB_PATH }}"
          - "{{ CHIA_SW_PATH }}"
          - "{{ ANSIBLE_HOME_PATH }}"
          - "{{ ANSIBLE_LOG_PATH }}"
    - name: "Set Active Testcases"
      ansible.builtin.set_fact:
        ACTIVE_TESTCASES: "{{ BENCHMARK_CONFIG.ACTIVE_TESTCASES }}"
    - name: "Set Test Scenario Variables" 
      ansible.builtin.set_fact:
        DB_BACKUP: "{{ BENCHMARK_CONFIG.SCENARIO[SCENARIO].DB_BACKUP_NAME }}"
        DB_BACKUP_URL: "{{ BENCHMARK_CONFIG.SCENARIO[SCENARIO].DB_BACKUP_URL }}"
        SYNC_START_HEIGHT: "{{ BENCHMARK_CONFIG.SCENARIO[SCENARIO].SYNC_START_HEIGHT }}" 
        DUST_START_HEIGHT: "{{ BENCHMARK_CONFIG.SCENARIO[SCENARIO].DUST_START_HEIGHT }}"
        DUST_STOP_HEIGHT: "{{ BENCHMARK_CONFIG.SCENARIO[SCENARIO].DUST_STOP_HEIGHT }}"
    - name: "Set Log File Path variable as fact before using for other assignments"
      ansible.builtin.set_fact:
        ANSIBLE_LOG_FILE_PATH: "{{ ANSIBLE_LOG_PATH }}/{{ timestamp_started.stdout }}"
    - name: "Set Logfiles paths/names"
      ansible.builtin.set_fact:
        ANSIBLE_LOG_FILE_NAME: "{{ ansible_hostname }}_ansible_run"
        ANSIBLE_LOG_SA_PATH: "{{ ANSIBLE_LOG_FILE_PATH }}/sa"
        ANSIBLE_LOG_CHIA_PATH: "{{ ANSIBLE_LOG_FILE_PATH }}/chia"
        CHIA_LOG_FILE_NAME: "{{ ansible_hostname }}_chia_debug"
    - name: "Create Log Directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ ANSIBLE_LOG_PATH }}"
        - "{{ ANSIBLE_LOG_FILE_PATH }}"
        - "{{ ANSIBLE_LOG_SA_PATH }}"
        - "{{ ANSIBLE_LOG_CHIA_PATH }}"
    - name: "Cleanup old link to log directory"
      ansible.builtin.file:
        path: "{{ ANSIBLE_LOG_PATH }}/current"
        state: absent
    - name: "Create Link to current log directory"
      ansible.builtin.file:
        src: "{{ ANSIBLE_LOG_FILE_PATH }}"
        dest: "{{ ANSIBLE_LOG_PATH }}/current"
        state: link
    - name: "Write logfile header"
      ansible.builtin.lineinfile:
        path: "{{ ANSIBLE_LOG_FILE_PATH }}/{{ ANSIBLE_LOG_FILE_NAME }}.csv"
        line: "HOSTNAME,SCENARIO,TESTCASE,START_RUN,LOG_INITIATE_SYNC,LOG_START_SYNC,LOG_DUST_START_SYNC,LOG_DUST_STOP_SYNC,SQLITE_DB_SIZE_BYTES,DESCRIPTION"
        create: yes
    - name: "Check if extracted sqlite db file for scenario {{ SCENARIO }} already exists"
      ansible.builtin.stat:
        path: "{{ BLOCKCHAIN_DB_PATH }}/{{ DB_BACKUP }}"
        get_checksum: no
        get_mime: no
      register: db_backup_already_extracted
    - name: "Extract sqlite db file for scenario {{ SCENARIO }}"
      ansible.builtin.unarchive:
        src: "{{ DB_BACKUP_URL }}"
        dest: "{{ BLOCKCHAIN_DB_PATH }}"
        remote_src: yes
      when: not db_backup_already_extracted.stat.exists 
  roles:
    - { role: setup_chia }
    - { role: run_sync_tests_for_active_testcases }
        #  tasks:
        #    - name: test
        #      debug: 
        #        msg: "{{ ansible_facts }}"
