---
- name: "Get current auto_vacuum configuration"
  ansible.builtin.shell: |
    sqlite3 {{ BLOCKCHAIN_DB_PATH }}/{{ BLOCKCHAIN_DB_NAME }} 'PRAGMA auto_vacuum;'
  register: db_auto_vacuum
- name: "Vacuum db to enable auto_vacuum={{ AUTO_VACUUM }}"
  ansible.builtin.shell: |
    sqlite3 {{ BLOCKCHAIN_DB_PATH }}/{{ BLOCKCHAIN_DB_NAME }} 'PRAGMA journal_mode=OFF; PRAGMA auto_vacuum={{ AUTO_VACUUM }}; VACUUM;'
  register: output
  when: "((AUTO_VACUUM == 'FULL' OR AUTO_VACUUM == 1) AND db_auto_vacuum != 1) OR ((AUTO_VACUUM == 'INCREMENTAL' OR AUTO_VACUUM == 2) AND db_auto_vacuum != 2)"
