---
- name: "Get current auto_vacuum configuration"
  ansible.builtin.shell: |
    sqlite3 {{ BLOCKCHAIN_DB_PATH }}/{{ BLOCKCHAIN_DB_NAME }} 'PRAGMA auto_vacuum;'
  register: db_auto_vacuum
- name: "Vacuum db to enable auto_vacuum={{ AUTO_VACUUM }}"
  ansible.builtin.shell: |
    sqlite3 {{ BLOCKCHAIN_DB_PATH }}/{{ BLOCKCHAIN_DB_NAME }} 'PRAGMA journal_mode=OFF; PRAGMA auto_vacuum={{ AUTO_VACUUM }}; VACUUM;'
  register: output
  when: "(db_auto_vacuum.stdout != 1 and 'AUTO_VACUUM|upper' == 'FULL') or (db_auto_vacuum.stdout != 2 and 'AUTO_VACUUM|upper' == 'INCREMENTAL')"
