---
- name:                      "Install generic packages"
  include_tasks:               generic.yml
- name:                      "Install os-dependent packages"
  include_tasks:               "{{ ansible_facts.os_family }}.yml"
