---
- name:                      "Install generic packages"
  import_file:               generic.yml
- name:                      "Install os-dependent packages"
  import_file:               "{{ ansible_facts.os_family }}.yml"
