---
- name: "Set Runtime (Testcase) Variables as fact"
  ansible.builtin.set_fact:
    ANSIBLE_SA_FILE_NAME: "{{ ansible_hostname }}_{{ ansible_date_time.epoch }}_{{ TESTCASE }}"
    DESCRIPTION: "{{ BENCHMARK_CONFIG[TESTCASE].DESCRIPTION | default(BENCHMARK_CONFIG.DEFAULT.DESCRIPTION) }}"
    CHIA_BRANCH: "{{ BENCHMARK_CONFIG[TESTCASE].CHIA_BRANCH | default(BENCHMARK_CONFIG.DEFAULT.CHIA_BRANCH) }}"
    CHANGE_PAGE_SIZE: "{{ BENCHMARK_CONFIG[TESTCASE].CHANGE_PAGE_SIZE | default(BENCHMARK_CONFIG.DEFAULT.CHANGE_PAGE_SIZE) }}"
    PAGE_SIZE: "{{ BENCHMARK_CONFIG[TESTCASE].PAGE_SIZE | default(BENCHMARK_CONFIG.DEFAULT.PAGE_SIZE) }}"
