---
CHIA_OS_USER: "chia"
CHIA_OS_GROUP: "chia"
CHIA_GIT_REPO: "https://github.com/Chia-Network/chia-blockchain.git"
CHIA_BRANCH: "1.2.11"
CUSTOM_LOGGING: "info"
ANSIBLE_REMOTE_TEMP: "/chia_temp1/.ansible/tmp"
SCENARIO: "FULLSYNC"
SADC_BIN_PATH: "/usr/lib64/sa"
BLOCKCHAIN_DB_NAME: "blockchain_v1_mainnet.sqlite"
BLOCKCHAIN_DB_PATH: "/chia_temp1/Blockchain_DB"
OS_USER_HOME: "/home/chia"
CHIA_SW_PATH: "/home/chia/chia-blockchain"
ANSIBLE_HOME_PATH: "/home/chia/chia-sync-test"
ANSIBLE_LOG_PATH: "/home/chia/chia-sync-test/log"
